name = "linear-opencode-agent"
main = "src/worker.ts"
compatibility_date = "2024-01-15"
node_compat = true

[triggers]
crons = []

[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[queues.producers]]
queue = "agent-sessions"
binding = "SESSION_QUEUE"

[[queues.consumers]]
queue = "agent-sessions"
max_batch_size = 10
max_batch_timeout = 30

[vars]
OPENCODE_MODEL = "deepseek/deepseek-r1-distill-llama-3.2-8b"
NODE_ENV = "production"

# Secrets (set with wrangler secret put)
# LINEAR_API_KEY
# LINEAR_WEBHOOK_SECRET
# DEEPSEEK_API_KEY
# GROQ_API_KEY
# PERPLEXITY_API_KEY
# TASKMASTER_API_KEY

[env.production]
name = "linear-opencode-agent-prod"
route = "agent.yourdomain.com/*"

[env.staging]
name = "linear-opencode-agent-staging"
route = "staging-agent.yourdomain.com/*"